name: Build and Push ARM64 Container Image

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 02:00 UTC every Tuesday.
    - cron: "0 2 * * 2"

jobs: 
  build-and-push: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build ARM64 Container image
        run: |
          podman build --platform linux/arm64 -t ghcr.io/wnd-zermatt/wnd-shell:latest-arm64 . 

      - name: Push ARM64 Container image
        run: |
          podman push ghcr. io/wnd-zermatt/wnd-shell:latest-arm64

      - name: Create and push manifest
        run: |
          podman manifest create ghcr.io/wnd-zermatt/wnd-shell:latest
          podman manifest add ghcr.io/wnd-zermatt/wnd-shell:latest ghcr.io/wnd-zermatt/wnd-shell:latest-arm64
          podman manifest push ghcr.io/wnd-zermatt/wnd-shell:latest
